# Generated by Django 3.2.19 on 2023-06-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_class_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
