# Generated by Django 3.2.19 on 2023-06-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_class_app', '0002_alter_workfile_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesToWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(default=None, max_length=250, null=True, upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkFile',
        ),
    ]
