# Generated by Django 3.2.19 on 2023-06-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_class_app', '0003_auto_20230608_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestowork',
            name='archivo',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='FilesToWork/'),
        ),
    ]
