# Generated by Django 3.2.19 on 2023-06-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_class_app', '0004_alter_filestowork_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(default=None, max_length=250, null=True, upload_to='Files/')),
            ],
        ),
        migrations.DeleteModel(
            name='FilesToWork',
        ),
    ]
