# Generated by Django 3.2.19 on 2023-06-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_class_app', '0008_alter_files_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='archivo',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Files/'),
        ),
    ]
