# Generated by Django 3.2.19 on 2023-06-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_class_app', '0010_alter_files_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algoritmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Esta es una descripción del algoritmo', max_length=1000)),
            ],
        ),
    ]
